project_id = "xgtwutpbojltmktprdui"

[functions.run-reminders]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.send-training-reminders]
verify_jwt = false

[functions.list-users]
verify_jwt = false