project_id = "xgtwutpbojltmktprdui"

[functions.run-reminders]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.send-training-reminders]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.run-deadline-reminders]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.admin-link-employee]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-change-email]
verify_jwt = true

[functions.admin-deactivate-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.run-medical-reminders]
verify_jwt = false

[functions.seed-initial-admin]
verify_jwt = false

[functions.apply-migrations]
verify_jwt = false